### ISSUE TITLE
解决旧版本在alfred打不开的问题

### ISSUE THREAD

**Issue by ae6623** [tong822218/baidu_translate_workflow#1]
如果发现在alfred中无法打开旧版本，提示python过期，可以尝试如下方法进行修复

访问
https://www.alfredapp.com/help/troubleshooting/incompatible-python-workflow-library/

执行下图命令即可

<img width="559" alt="20190218224242" src="https://user-images.githubusercontent.com/3894033/52958241-a2da3600-33ce-11e9-9f9e-871722dfb586.png">

**Comment by ae6623** [comment]
如果使用 DD 无法触发翻译，可能是原作者的开发者账号Id以及密钥过期了，建议想使用的，可以自己注册一个，比较简单。百度开发者账号注册：http://api.fanyi.baidu.com/api/trans/product/desktop?req=developer

**Comment by ae6623** [comment]
顺便推荐一个有道翻译的插件
https://blog.julysong.com/2018/07/05/Alfred-youdao/

**Comment by tong822218** [comment]
哈哈，没想到还有朋友提issue. 感谢
